"""create appliation table

Revision ID: a004b568a11f
Revises: ec3eceeaff6b
Create Date: 2026-05-30 15:51:29.735446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a004b568a11f'
down_revision: Union[str, Sequence[str], None] = 'ec3eceeaff6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_path', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'resume_path')
    # ### end Alembic commands ###
